### ISSUE TITLE
Připrav základní content strategy

### ISSUE THREAD

**Issue by f4z4on** [budoucnost/web#1]
Předně je dobré říci, že naše content strategy zatím bude nejspíš minimalistická. Hlavní vstupem do ní bude Lean Canvas a debata s členstvem komunikační skupiny a jejích podskupin nebo alespoň s garantkou skupiny.

**Comment by f4z4on** [comment]
Osobně mi jako dobrý odpíchnutí přijdou tyhle články:

* [The Discipline of Content Strategy](https://alistapart.com/article/thedisciplineofcontentstrategy/) od Kristiny Halvorson,
* [Content-tious Strategy](https://alistapart.com/article/contenttiousstrategy/) od Jeffreyho MacIntyra, které jsou hodně seminální v blogosféře, a třeba
* [The Content Corner: Building a Content Strategy](https://digital.gov/2015/03/23/the-content-corner-building-a-content-strategy/) od Tyruse Manuela z administrativy USA, která za Obamy nastartovala příkladné změny celého federálního behemota k dobrým digitální službám (tzn. něčemu, co slouží dobře ☺️).

V nich jsou termíny a dobré odkazy, kdy už se dá surfovat a zkoumat. Zajímavé je taky zkusit hledat tyhle články a zjistit, kde a jak se na ně lidi odkazují. Články, které tě zaujmout prosím sdílej, nebo zaznamenávej. Jednak udržíme nějakou vlastní kontinuitu a kontext rozhodnutí jako skupina. Potom se ale můžeme bavit i o tom, jestli takový článek (resp. jeho autora či autorku) vnímat jako autoritativní.

Zároveň můžu zapůjčit [kratší a praktickou knihu od A Book Apart](https://abookapart.com/products/content-strategy-for-mobile). Sice zaměřuje na mobilní svět, ale to je upřímně spíš to, co bychom měli chtít 😊

**Comment by f4z4on** [comment]
Teď koukám, že mám ještě jednu [starší knihu o content strategy taky od A Book Apart](https://abookapart.com/products/the-elements-of-content-strategy), která je možná lepší. Nevím, se přiznám, že tuhle jsem kdysi dávno jenom načal a tu, co jsem zmiňoval dříve, jsem ani neotevřel 😞

**Comment by MrtnMtl** [comment]
Díky moc za výše poskytnuté články. Jsou dost obecné, a musím přiznat, že pro mně plné bezobsažné marketing/business filler words a vět, který nedávají smysl v jakýmkoliv jiným kontextu, ale prokousal jsem to. To bude jen moje osobní antipatie vůči takovýmu prostředí plným buzzwords a tech keců. 

Přišly mi ale užitečné, potom jsem hledal praktičtější články a návody, abych mohl skočit rovnou do toho. Sem budu přidávat zdroje, které použítám.
[Building a Killer Content Strategy](https://images.template.net/wp-content/uploads/2016/03/03072135/Building-A-Killer-Content-Strategy.pdf)
Dělám si z nich všech výpisky, tak to budu průběžně updateovat. 

V plánu mám odpíchnout se od Lean Canvassu, od mé analýzy ostatních webů a od našich customer segmentů, které chci více rozkreslit. Zítra dokončím rešeršní práce a v nedělu se plně vrhnu na tvorbu samé content strategy.

**Comment by MrtnMtl** [comment]
Zdarec, chci s vámi sdílet svůj progress v tvorbě content strategy. Ve zkratce: vytvořil jsem dokument, kde popisuju proces tvorby content strateie.
Key features:
Ten proces je iterativní, škálovatelný a flexibilní, a popisuje, jak můžeme postavit web z ničeho, upravit web nebo úplně změnit jeho účel.
Bere v potaz existující stav, input cílových skupin uživatelů a zadání komunikační skupiny.
Tvoří dodatečné guidelines, předpisy, benchmarks atp., podle kterých se dá vyhodnocovat.
Vše co mně napadlo o tom procesu najdete v tomto dokumentu. Jestli vás napadá, že tam něco chybí, rád přidám. Jestli jdu špatným směrem, taky mi dejte vědět :slightly_smiling_face:
Pokud je vše OK, po dnešním callu bych začal práci na první iteraci tohoto procesu s cílem vytvořit první content strategy pro náš web,

DOKUMENT NAJDETE NA SLACKU, TADY JEŠTĚ NEVIM JAK SE UPLOADUJE :)

**Comment by f4z4on** [comment]
> Tady ještě nevím, jak se uploaduje

Upload, byť teoreticky možný, není zrovna správný postup. Dokument by měl být převedený do [wiki](/budoucnost/web/wiki).

**Comment by f4z4on** [comment]
Issue uzavírám. Práce je součástí jednotného dokumentu spolu s výsledky práce na informační architektuře a tým na tom pracuje kontinuálně. Dokument pro teď není veřejný – zveřejnění by vyžadovalo úpravy, tj. zdržení týmu v momentě, kdy zrovna nemáme čas.
