### ISSUE TITLE
Oprav indexovatelnost webu

### ISSUE THREAD

**Issue by f4z4on** [budoucnost/web#3]
Web není indexovaný vyhledávači. [Google][] sice při zadání dotazu „budoucnost hnutí“ vrátí na druhém místě náš web, nicméně bez popisu. Google API (např. přes [Startpage][]) a další vyhledávače jako [Bing][] (a tedy i [DuckDuckGo][]) nebo [Seznam.cz][] náš web ve výsledcích nemají.

Tahle query přitom obsahuje term, který je v `<title>`. Kdyby někdo hledal podle termínů z programových pilírů, tak se našeho webu určitě nedohledá.

[Google]: https://www.google.com/search?q=budoucnost+hnutí
[Startpage]: https://www.startpage.com/sp/search?query=budoucnost+hnutí
[Bing]: https://www.bing.com/search?q=budoucnost+hnutí
[DuckDuckGo]: https://duckduckgo.com/?q=budoucnost+hnutí
[Seznam.cz]: https://search.seznam.cz/?q=budoucnost+hnutí

**Comment by f4z4on** [comment]
Naivně se zdá, že rychlým řešením by mohlo být prosté zkopírování celého DOM, jehož významnou část generuje React appka. Výsledek dát do index.html. Potom vyřešit to, co touhle operací přestane fungovat – dynamické elementy, obrázky, formuláře, CSS, …

**Comment by bganicky** [comment]
Ja teda v Google popisek vidim. Jenom je takovy nahodny. Mozna by do zacatku uplne stacilo tam vyplnit meta description. V dalsi fazi bude urcite dobre neco poslat uz ze serveru. Ale asi nejdriv bude treba rict, na jakem stacku to vubec bude cele udelane.
